#!/usr/bin/env bash

set -eou pipefail

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

gpus=0

nj=16
stage=4
stop_stage=4

dl_dir=/data6/zhanghongbin/datasets/data_aishell3
dump_dir=/data6/zhanghongbin/projects/PaddleSpeech/examples/aishell3/tts3/dump_not_cut-sil

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "dl_dir: $dl_dir"

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Train aishell3"

  # nano
  CUDA_VISIBLE_DEVICES=${gpus} python3 bin/trainer.py \
    --decoder-dim 256 --nhead 4 --num-decoder-layers 6 \
    --exp-dir exp/vallf_nano \
    --training-start-frame 60 \
    --num-epochs 100 \
    --base-lr 0.0005 \
    --model-name "VALL-F" \
    --max-duration 30
    # --world-size 3
    # --deepspeed --deepspeed_config configs/ds_zero2.config

  # same as paper
  # python3 bin/trainer.py \
  #   --decoder-dim 1024 --nhead 16 --num-decoder-layers 12 \
  #   --exp-dir exp/valle
fi
